[server]
port = 8501
headless = true
enableCORS = true
enableXsrfProtection = true


[theme]
base="dark"
primaryColor="#00BCD4"
backgroundColor="#1C1E21"
secondaryBackgroundColor="#282C34"
textColor="#E0E0E0"
font="sans serif"
